
C:\MEUS PROJETOS\GITHUB\django-simple-ecommerce-master>pytho    autoreload.check_errors(django.setup)()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Pythn manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 357, in execute
on39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'crispy_forms'
Traceback (most recent call last):
  File "C:\MEUS PROJETOS\GITHUB\django-simple-ecommerce-master\manage.py", line 21, in <module>
    main()
  File "C:\MEUS PROJETOS\GITHUB\django-simple-ecommerce-master\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 96, in handle
    self.run(**options)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 614, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 599, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 314, in run
    self.run_loop()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 320, in run_loop
    next(ticker)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 360, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 376, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 274, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1204, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta: '<frozen importlib._bootstrap>'

C:\MEUS PROJETOS\GITHUB\django-simple-ecommerce-master>